config/routes.rb
Mepalex::Application.routes.draw do
  devise_for :users

  # Administration routes
  get 'admin' => redirect('/admin/auctions')
  namespace :admin do
    resources :auctions do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :ad_posts do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :newsletters do
      post 'mail', :on => :member
    end
    resources :images do
      post 'sort', :on => :collection
    end
  end

  # Public routes
  get   'contact'          => 'contact_messages#new',    :as => 'new_contact_message'
  post  'contact'          => 'contact_messages#create', :as => 'contact_messages'
  get   'encans/:slug'     => 'auctions#show',           :as => 'auction'
  get   'encans'           => 'auctions#index',          :as => 'auctions'
  get   'babillard/:slug'  => 'ad_posts#show',           :as => 'ad_post'
  get   'babillard'        => 'ad_posts#index',          :as => 'ad_posts'
  get   'a-propos'         => 'about#index',             :as => 'about'
  get   'mail/:newsletter_id' => 'homepage#mail',        :as => 'mail'

  root :to => 'homepage#show'
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  caches_page :show

  def show
    @auctions = Auction
                .where(:published => true)
                .where(["date >= ?", Date.today])
                .order("date ASC")
                .includes(:images)
                .limit(2)
    @ads = AdPost
           .where(:published => true)
           .order("created_at DESC")
           .includes(:images)
           .limit(2)
  end

  def mail
    @newsletter = Newsletter.find(params[:newsletter_id])
    render :template => 'newsletter_mailer/newsletter', :layout => false
  end
end

app/views/homepage/_ad_post.html.erb
<div class="eight columns <%= index == 0 ? 'alpha' : 'omega' %>">
  <div class="item-box ad-post clearfix">
    <div class="links">
      <div class="padding">
        <a href="<%= ad_post_path(ad_post.slug_with_id) %>">
        <% if !ad_post.image.blank? %>
          <%= image_tag ad_post.image.url(:thumb), :class => "scale-with-grid", :width => 160, :height => 120 %>
        <% else %>
          <%= image_tag 'home/main-encans-babillard-thumbnails-pas-disponible.jpg', :class => "scale-with-grid", :width => 160, :height => 120 %>
        <% end %>
        </a>
        <ul class="quick-links">
          <li><%= link_to "En savoir plus", ad_post_path(ad_post.slug_with_id), :class => "icon-glass" %></li>
        </ul>
      </div>
    </div>
    <div class="info">
      <div class="padding">
        <h1><%= link_to ad_post.title, ad_post_path(ad_post.slug_with_id) %></a></h1>
        <%= markdown(ad_post.short_description) %>
      </div>
    </div>
  </div>
</div>

app/views/homepage/_auction.html.erb
<div class="eight columns <%= index == 0 ? 'alpha' : 'omega' %>">
  <div class="item-box auction clearfix">
    <div class="links">
      <div class="padding">
        <a href="<%= auction_path(auction.slug_with_id) %>">
        <% if !auction.image.blank? %>
          <%= image_tag auction.image.url(:thumb), :class => "scale-with-grid", :width => 160, :height => 120 %>
        <% else %>
          <%= image_tag 'home/main-encans-babillard-thumbnails-pas-disponible.jpg', :class => "scale-with-grid", :width => 160, :height => 120 %>
        <% end %>
        </a>
        <ul class="quick-links">
          <li><%= link_to "En savoir plus", auction_path(auction.slug_with_id), :class => "icon-glass" %></li>
          <% unless auction.pdf.blank? %>
            <li><%= link_to "Circulaire de l’encan", auction.pdf.url, :class => "icon-pdf" %></li>
          <% end %>
          <% unless auction.catalog.blank? %>
            <li><%= link_to "Catalogue", auction.catalog.url, :class => "icon-pdf" %></li>
          <% end %>
          <% if auction.geocoded? %>
            <li><%= link_to "Voir sur la carte", auction.google_map, :class => "icon-map" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="info">
      <div class="time">
        <time datetime="<%=auction.date%>"><%= l(auction.date, :format => :long) %> <%= auction.start_time %></time>
      </div>
      <div class="padding">
        <h1><%= link_to auction.title, auction_path(auction.slug_with_id) %></a></h1>
        <%= markdown(auction.short_description) %>
        <p><%= auction.address %></p>
      </div>
    </div>
  </div>
</div>

app/views/homepage/show.html.erb
<% content_for :open_graph do %>
  <meta property="og:url" content="<%= root_url %>"/>
  <meta property="og:type" content="company"/>
  <meta property="og:title" content="Encans Daniel Paul-Hus | Encanteur bilingue spécialisé dans l'industrie agricole"/>
  <meta property="og:site_name" content="Encans Daniel Paul-Hus"/>
  <meta property="og:description" content="Daniel Paul-Hus est un encanteur bilingue spécialisé dans le milieu agricole depuis plus de 40 ans. Acheteur de fermes complètes, troupeaux et roulants de ferme."/>
  <meta property="og:image" content="<%= "http://#{request.host}#{image_path('star.png')}" %>"/>
<% end %>
<% content_for(:body_classes) { 'home-page' } %>
<% page_description "Daniel Paul-Hus est un encanteur bilingue spécialisé dans le milieu agricole depuis plus de 40 ans. Acheteur de fermes complètes, troupeaux et roulants de ferme." %>

<div class='slideshow sixteen columns'>
  <div id="home_slideshow">
    <div><%= image_tag 'home/homepage-slider-1.jpg', width: 940, height: 400 %></div>
    <div><%= image_tag 'home/homepage-slider-2.jpg', width: 940, height: 400 %></div>
    <div><%= image_tag 'home/homepage-slider-3.jpg', width: 940, height: 400 %></div>
  </div>
</div>

<%= render :partial=> 'partials/newsletter_promo' %>
<div class="sixteen columns clearfix">
  <hr class="hr"/>
</div>

<div class="sixteen columns">
  <h1>Prochains encans <span>/</span> <%= link_to "Voir tous les encans", auctions_path %></h1>

  <% @auctions.each_slice(2) do |row| %>
    <div class="row">
      <% if row.size == 2 %>
        <%= render :partial => 'homepage/auction', :locals => { :auction => row[0], :index => 0 } %>
        <%= render :partial => 'homepage/auction', :locals => { :auction => row[1], :index => 1 } %>
      <% else %>
        <%= render :partial => 'homepage/auction', :locals => { :auction => row[0], :index => 0 } %>
      <% end %>
    </div>
  <% end %>

  <h1>À vendre sur le babillard <span>/</span> <%= link_to "Voir tout le babillard", ad_posts_path %></h1>

  <% @ads.each_slice(2) do |row| %>
    <div class="row">
      <% if row.size == 2 %>
        <%= render :partial => 'ad_post', locals: {ad_post: row[0], :index => 0 } %>
        <%= render :partial => 'ad_post', locals: {ad_post: row[1], :index => 1 } %>
      <% else %>
        <%= render :partial => 'ad_post', locals: {ad_post: row[0], :index => 1 } %>
      <% end %>
    </div>
  <% end %>
</div>

<% content_for :javascripts do %>
  <script>
    $(function() {
      $('#home_slideshow').slick({
        infinite: true,
        autoplay: true
      });
    });
  </script>
<% end %>