config/routes.rb
Mepalex::Application.routes.draw do
  devise_for :users

  # Administration routes
  get 'admin' => redirect('/admin/auctions')
  namespace :admin do
    resources :auctions do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :ad_posts do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :newsletters do
      post 'mail', :on => :member
    end
    resources :images do
      post 'sort', :on => :collection
    end
  end

  # Public routes
  get   'contact'          => 'contact_messages#new',    :as => 'new_contact_message'
  post  'contact'          => 'contact_messages#create', :as => 'contact_messages'
  get   'encans/:slug'     => 'auctions#show',           :as => 'auction'
  get   'encans'           => 'auctions#index',          :as => 'auctions'
  get   'babillard/:slug'  => 'ad_posts#show',           :as => 'ad_post'
  get   'babillard'        => 'ad_posts#index',          :as => 'ad_posts'
  get   'a-propos'         => 'about#index',             :as => 'about'
  get   'mail/:newsletter_id' => 'homepage#mail',        :as => 'mail'

  root :to => 'homepage#show'
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mepalex</title>
  <%= stylesheet_link_tag "admin/application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/admin">Mepalex</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Auctions", admin_auctions_path %>
          </li>
          <li>
            <%= link_to "Ads", admin_ad_posts_path %>
          </li>
          <li>
            <%= link_to "Newsletters", admin_newsletters_path %>
          </li>
        </ul>
        <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <%= javascript_include_tag "admin/application" %>
  <%= yield :javascripts %>
</body>
</html>