config/routes.rb
Mepalex::Application.routes.draw do
  devise_for :users

  # Administration routes
  get 'admin' => redirect('/admin/auctions')
  namespace :admin do
    resources :auctions do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :ad_posts do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :newsletters do
      post 'mail', :on => :member
    end
    resources :images do
      post 'sort', :on => :collection
    end
  end

  # Public routes
  get   'contact'          => 'contact_messages#new',    :as => 'new_contact_message'
  post  'contact'          => 'contact_messages#create', :as => 'contact_messages'
  get   'encans/:slug'     => 'auctions#show',           :as => 'auction'
  get   'encans'           => 'auctions#index',          :as => 'auctions'
  get   'babillard/:slug'  => 'ad_posts#show',           :as => 'ad_post'
  get   'babillard'        => 'ad_posts#index',          :as => 'ad_posts'
  get   'a-propos'         => 'about#index',             :as => 'about'
  get   'mail/:newsletter_id' => 'homepage#mail',        :as => 'mail'

  root :to => 'homepage#show'
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  # Validation
  validates_presence_of :title, :date, :address, :slug

  attr_accessor :skip_processing

  # Defines which attribute is used to try to find the longitude
  # and latitude of this auction.
  geocoded_by :address_for_geocoding

  # The primary image of this auction. Used in the listings and such.
  mount_uploader :image, ImageUploader

  # The PDF version of the detailed text of this auction.
  mount_uploader :pdf, PdfUploader

  # The PDF version of the catalog of this auction.
  mount_uploader :catalog, PdfUploader

  # The images associated with this auction. The user can define
  # the order of the images using the position attribute.
  has_many :images, -> { order('position ASC') }, :as => :parent, :dependent => :destroy

  # Callbacks
  after_validation :geocode

  # Scopes
  scope :upcoming, -> { where("date >= ?", Date.current).ordered_by_date }
  scope :published, -> { where(:published => true) }
  scope :ordered_by_date, -> { order("date ASC") }

  class << self
    # Finds an auction using a slug with id.
    #
    # @param slug [String] The slug of the auction prefixed by its ID.
    # @return [Auction] If a post was found.
    # @return [nil] If a post was not found.
    def find_by_slug_with_id(slug)
      where(:id => slug.split("-").first.to_i).limit(1).first
    end
  end

  def skip_processing
    false
  end

  # Returns the url to the google map for this auction.
  #
  # @return [String] the url if the auction has coordinates.
  # @return [nil] if the auction doesn’t have coordinates.
  def google_map
    "http://maps.google.com/maps?q=#{latitude}+#{longitude}" if geocoded?
  end

  # @return [Boolean] is the auction geocoded?
  def geocoded?
    return true if google_maps_url
    !!(latitude && longitude)
  end

  # Returns a slug that looks like '5-the-auction-title'
  # @return [String] the slug for this auction
  def slug_with_id
    "#{id}-#{slug}"
  end

  def google_maps_url=(url)
    matches = url.match(/src="(\S+)"/)
    url = matches[1] if matches
    write_attribute(:google_maps_url, url)
  end

  # Sets the slug of this auction. It makes sure that the slug
  # is URI friendly.
  def slug=(slug)
    write_attribute :slug, slug.parameterize
  end

  # Returns true if the date of the auction is passed.
  #
  # @return [Boolean] is the auction passed or not.
  def outdated?
    Date.current > date
  end

  # Custom setter because my mom keeps putting spaces before/after
  # parenthesises when she should not.
  def title=(value)
    value.gsub!(/\( /, '(')
    value.gsub!(/ \)/, ')')
    write_attribute(:title, value)
  end
end

app/controllers/admin/auctions_controller.rb
class Admin::AuctionsController < Admin::ApplicationController
  cache_sweeper :auction_sweeper
  before_filter :find_auction, :only => [:edit, :update, :destroy, :show]

  def index
    @auctions = Auction
                .order("date ASC")
                .where("date >= ?", Date.today)
                .page(params[:page])
                .per(25)
  end

  def new
    @auction = Auction.new
    @auction.published = false
  end

  def create
    @auction = Auction.create(auction_params)
    redirect_to [:admin, @auction]
  end

  def edit; end

  def update
    @auction.update_attributes(auction_params)
    redirect_to [:admin, @auction]
  end

  def destroy
    @auction.destroy
    redirect_to [:admin, :auctions]
  end

  def show; end

  private

  def find_auction
    @auction = Auction.find(params[:id])
  end

  def auction_params
    safe_attributes = [
      :title, :slug, :short_description, :body, :address,
      :image, :pdf, :catalog, :date, :start_time, :published,
      :google_maps_url, :address_for_geocoding
    ]
    params.require(:auction).permit(safe_attributes)
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  caches_page :index, :show

  def index
    @auctions = Auction.published.upcoming
  end

  def show
    @auction = Auction.find_by_slug_with_id(params[:slug])
    raise ActiveRecord::RecordNotFound unless @auction
    raise ActiveRecord::RecordNotFound if @auction.outdated?
  end
end

app/views/admin/auctions/_form.html.erb
<fieldset>
  <div class="">
    <div class="form-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :slug, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :slug, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :short_description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :short_description, cols: 120, rows: 5, :class => 'span5 form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :body, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, cols: 120, rows: 5, :class => 'form-control span5' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :address, cols: 120, rows: 2, :class => 'form-control span5' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :address_for_geocoding, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :address_for_geocoding, cols: 120, rows: 2, :class => 'form-control span5' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :google_maps_url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :google_maps_url, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :image, :class => 'form-control span5' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :pdf, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :pdf %>
      </div>
      <% if f.object.pdf_url %>
        <%= f.label :remove_pdf, :class => "checkbox" do %>
          <%= f.check_box :remove_pdf %> Remove pdf
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :catalog, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :catalog %>
      </div>
      <% if f.object.catalog_url %>
        <%= f.label :remove_catalog, :class => "checkbox" do %>
          <%= f.check_box :remove_catalog %> Remove catalog
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :date, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :date, {}, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :start_time, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :start_time, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :published, :class => "checkbox" do %>
        <%= f.check_box :published %> Published
      <% end %>
    </div>
  </div>
</fieldset>

app/views/admin/auctions/edit.html.erb
<div class="page-header">
  <h1>Update an auction</h1>
</div>

<%= form_for [:admin, @auction] do |f| %>
  <%= render :partial => 'form', :locals => {f: f} %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
    <%= link_to "Back", [:admin, :auctions], :class => "btn" %>
  </div>
<% end %>

app/views/admin/auctions/index.html.erb
<div class="page-header">
  <h1>Auctions</h1>
</div>

<div>
  <%= link_to "Add an auction", [:new, :admin, :auction], :class => 'btn btn-primary' %>
</div>

<% unless @auctions.empty? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @auctions.each do |a| %>
        <tr>
          <td><%= a.title %></td>
          <td><%= l(a.date) %></td>
          <td>
            <%= link_to 'Manage', admin_auction_path(a), :class => 'btn btn-xs btn-default ' %>
            <%= link_to 'Edit', edit_admin_auction_path(a), :class => 'btn btn-xs btn-default ' %>
            <%= link_to 'Post', new_admin_auction_status_update_path(a), :class => 'btn btn-xs btn-default ' %>
            <%= link_to 'Destroy', admin_auction_path(a), :method => :delete,
              :data => {:confirm => "Are you sure?"}, :class => "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= paginate @auctions %>

app/views/admin/auctions/new.html.erb
<div class="page-header">
  <h1>Create an auction</h1>
</div>

<%= form_for [:admin, @auction] do |f| %>
  <%= render :partial => 'form', :locals => {f: f} %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
    <%= link_to "Back", [:admin, :auctions], :class => "btn" %>
  </div>
<% end %>

app/views/admin/auctions/show.html.erb
<div class="page-header">
  <h1><%= @auction.title %></h1>
</div>

<%= form_tag admin_images_path, multipart: true, :html => {:role => 'form'} do %>
  <div class="form-group">
    <%= file_field_tag 'images[]', multiple: true, :class => 'form-control' %>
    <%= hidden_field_tag 'parent_type', 'Auction' %>
    <%= hidden_field_tag 'parent_id', @auction.id %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Upload</button>
  </div>
<% end %>

<% unless @auction.images.empty? %>
  <table class="table" data-update-url="<%= sort_admin_images_path %>">
    <thead>
      <tr>
        <th>Image</th>
        <th>Caption</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @auction.images.each do |image| %>
      <tr id="image_<%= image.id %>">
        <td><%= image_tag image.file.url(:small_square) %></td>
        <td>
          <span class="rest-in-place" data-url="<%= admin_image_path(image.id) %>" data-object="image" data-attribute="caption">
            <% if !image.caption.empty? %>
              <%= image.caption %>
            <% else %>
              Click here to set a caption.
            <% end %>
          </span>
        </td>
        <td>
          <%= link_to 'Destroy', admin_image_path(image), :method => :delete,
            :data => {:confirm => "Are you sure?"}, :class => "btn btn-xs btn-danger" %>
          <a class="move btn btn-xs btn-default">
            <span class="glyphicon glyphicon-move"></span> move
          </a>
        </td>
      </tr>
      <% end %>
    </tbody/
  </table>
<% end %>

<% content_for :javascripts do %>
<script type="text/javascript">
$(function() {
  $('table.table').sortable({
    axis: 'y',
    items: "tbody tr",
    handle: ".move",
    forcePlaceholderSize: true,
    helper: function(e, tr) {
      var $originals = tr.children();
      var $helper = tr.clone();
      $helper.children().each(function(index) {
        // Set helper cell sizes to match the original sizes
        $(this).width($originals.eq(index).width())
      });
      return $helper;
    },
    update: function() {
      $.post($(this).data('update-url'), $(this).sortable('serialize'));
    }
  });
});
</script>
<% end %>