config/routes.rb
Mepalex::Application.routes.draw do
  devise_for :users

  # Administration routes
  get 'admin' => redirect('/admin/auctions')
  namespace :admin do
    resources :auctions do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :ad_posts do
      resources :status_updates, :only => [:new, :create]
      resources :images
    end
    resources :newsletters do
      post 'mail', :on => :member
    end
    resources :images do
      post 'sort', :on => :collection
    end
  end

  # Public routes
  get   'contact'          => 'contact_messages#new',    :as => 'new_contact_message'
  post  'contact'          => 'contact_messages#create', :as => 'contact_messages'
  get   'encans/:slug'     => 'auctions#show',           :as => 'auction'
  get   'encans'           => 'auctions#index',          :as => 'auctions'
  get   'babillard/:slug'  => 'ad_posts#show',           :as => 'ad_post'
  get   'babillard'        => 'ad_posts#index',          :as => 'ad_posts'
  get   'a-propos'         => 'about#index',             :as => 'about'
  get   'mail/:newsletter_id' => 'homepage#mail',        :as => 'mail'

  root :to => 'homepage#show'
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_and_belongs_to_many :auctions
  has_and_belongs_to_many :ad_posts

  def mail
    I18n.with_locale(:fr) do
      create_campaign
    end
  end

  protected

  def create_campaign
    api = Mailchimp::API.new(Mepalex::Application.config.mailchimp[:api_key])
    campaign = api.campaigns.create "regular", campaign_options, campaign_content
    api.campaigns.send(campaign["id"])
  end

  def campaign_options
    {
      :list_id => '159924ed0d',
      :subject => "Lettre d'information du #{I18n.l(Date.current, :format => :long)}",
      :from_email => 'noreply@paul-hus.com',
      :from_name => 'Daniel Paul-Hus',
      :inline_css => true
    }
  end

  def campaign_content
    mailer = NewsletterMailer.newsletter(self)
    content = {
      :html => mailer.html_part.body.to_s,
      :text => mailer.text_part.body.to_s
    }
  end
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < Admin::ApplicationController
  before_filter :find_newsletter, :only => [:edit, :update, :destroy, :show, :mail]

  def index
    @newsletters = Newsletter.order("created_at DESC")
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    @newsletter = Newsletter.new(newsletter_params)
    if @newsletter.save
      redirect_to admin_newsletters_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @newsletter.update_attributes(newsletter_params)
    if @newsletter.save
      redirect_to admin_newsletters_path
    else
      render :edit
    end
  end

  def destroy
    @newsletter.destroy
    redirect_to admin_newsletters_path
  end

  def show
  end

  def mail
    @newsletter.mail
    redirect_to admin_newsletters_path
  end

  protected

  def find_newsletter
    @newsletter = Newsletter.find(params[:id])
  end

  def newsletter_params
    safe_attributes = [:body, :caption, :auction_ids => [], :ad_post_ids => []]
    params.require(:newsletter).permit(safe_attributes)
  end
end

app/views/admin/newsletters/_form.html.erb
<fieldset>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label' %>
    <%= f.text_area :body, cols: 120, rows: 5, :class => 'form-control' %>
  </div>
</fieldset>

app/views/admin/newsletters/edit.html.erb
<div class="page-header">
  <h1>Update a newsletter</h1>
</div>

<%= form_for [:admin, @newsletter] do |f| %>
  <%= render :partial => 'form', :locals => {f: f} %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
    <%= link_to "Back", [:admin, :newsletters], :class => "btn" %>
  </div>
<% end %>

app/views/admin/newsletters/index.html.erb
<div class="page-header">
  <h1>Newsletters</h1>
</div>

<div>
  <%= link_to "Add a newsletter", [:new, :admin, :newsletter], :class => 'btn btn-primary' %>
</div>

<% unless @newsletters.empty? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @newsletters.each do |n| %>
        <tr>
          <td><%= n.id %></td>
          <td>
            <%= link_to 'Manage', admin_newsletter_path(n), :class => 'btn btn-xs btn-default' %>
            <%= link_to 'Edit', edit_admin_newsletter_path(n), :class => 'btn btn-xs btn-default' %>
            <%= link_to 'Destroy', admin_newsletter_path(n), :method => :delete,
              :data => {:confirm => "Are you sure?"}, :class => "btn btn-xs btn-danger" %>
            <%= link_to 'Mail', mail_admin_newsletter_path(n), :method => :post,
              :data => {:confirm => "Are you sure?"}, :class => "btn btn-xs btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/newsletters/new.html.erb
<div class="page-header">
  <h1>Create a newsletter</h1>
</div>

<%= form_for [:admin, @newsletter] do |f| %>
  <%= render :partial => 'form', :locals => {f: f} %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
    <%= link_to "Back", [:admin, :newsletters], :class => "btn" %>
  </div>
<% end %>

app/views/admin/newsletters/show.html.erb
<%= form_for [:admin, @newsletter] do |f| %>
  <fieldset>
    <legend>Auctions</legend>

    <% Auction.upcoming.each do |auction| %>
      <div>
        <%= check_box_tag 'newsletter[auction_ids][]', auction.id, @newsletter.auctions.include?(auction) %>
        <%= auction.title %> <%= l(auction.date) %>
      </div>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Posts</legend>
    <% AdPost.all.each do |post| %>
      <div>
        <%= check_box_tag 'newsletter[ad_post_ids][]', post.id, @newsletter.ad_posts.include?(post) %>
        <%= post.title %>
      </div>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= link_to "Cancel", admin_newsletters_path, :class => "btn" %>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
<% end %>